default:
	cat Makefile

run:
	npx react-native start
	
run_android:
	npx react-native run-android

run_ios:
	npx react-native run-ios
    # or • Open app_getting_started_reactnative_cli/ios/app_getting_started_reactnative_cli.xcworkspace in Xcode or run "xed -b ios"
    #    • Hit the Run button
